#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [[ $# -lt 1 ]] ; then
	pkgcore_helper_exit 1 "dobin: at least one arguement needed"
fi


if [[ ! -d ${D}${DESTTREE}/bin ]] ; then
	install -d "${D}${DESTTREE}/bin"
	pkgcore_helper_check_exit $? "failed installing base directory ${D}${DESTTREE}/bin; D=${D}, DESTTREE=${DESTTREE}"
fi

ret=0

for x in "$@" ; do
	if [[ -e ${x} ]] ; then
		install -m0755 -o ${PORTAGE_INST_UID:-0} -g ${PORTAGE_INST_GID:-0} "${x}" "${D}${DESTTREE}/bin"
	else
		echo "!!! ${0##*/}: ${x} does not exist" 1>&2
		false
	fi
	((ret+=$?))
done

pkgcore_helper_exit ${ret}
