#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

slash=/
install -d ${DIROPTIONS} "${@/#${slash}/${D}${slash}}"
pkgcore_helper_exit ${?}
