#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [[ $# -lt 1 ]] ; then
	pkgcore_helper_exit 1 "at least one arguement needed, none given"
fi

env \
INSDESTTREE="/etc/env.d/" \
doins "$@"
pkgcore_helper_exit $? "doenvd invocation of doins failed"
