#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [ -z "${PKGCORE_BIN_PATH}" ]; then
	echo "PKGCORE_BIN_PATH is unset!"
	exit -1
fi

if [[ $# -lt 1 ]] ; then
	pkgcore_helper_exit 1 "at least one arguement needed"
fi

if [[ ! -d ${D}${EXEDESTTREE} ]] ; then
	install -d "${D}${EXEDESTTREE}"
	pkgcore_helper_check_exit $? "install of base directory failed; \${D}=${D}, \${EXEDESTTREE}=${EXEDESTTREE}"
fi

ret=0
for x in "$@" ; do
	if [ -L "${x}" ] ; then
		if ! cp "${x}" "${T}"; then
			echo "warning, cp to temp space failed, skipping" >&2
			((ret|=1))
			continue
		fi

		mysrc="${T}"/$(/usr/bin/basename "${x}")
		if [ $? != 0 ]]; then
			echo "warning: basename failed for ${x}; skipping" >&2
			((ret|=1))
			continue
		fi
	elif [ -d "${x}" ] ; then
		echo "doexe: warning, skipping directory ${x}"
		continue
	else
		mysrc="${x}"
	fi
	install ${EXEOPTIONS} "${mysrc}" "${D}${EXEDESTTREE}"
	((ret|=$?))
done

pkgcore_helper_exit $ret
