#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [ -z "${PKGCORE_BIN_PATH}" ]; then
	echo "PKGCORE_BIN_PATH is unset!"
	exit -1
fi
source "${PKGCORE_BIN_PATH}/isolated-functions.lib" || {
	"failed sourcing isolated-function.sh"; exit 1;
}

if [[ $# -lt 1 ]] ; then
	echo "$0: at least one argument needed" 1>&2
	exit 1
fi

if [[ ! -d ${D}${EXEDESTTREE} ]] ; then
	install -d "${D}${EXEDESTTREE}"
fi

for x in "$@" ; do
	if [ -L "${x}" ] ; then
		cp "${x}" "${T}"
		mysrc="${T}"/$(/usr/bin/basename "${x}")
	elif [ -d "${x}" ] ; then
		echo "doexe: warning, skipping directory ${x}"
		continue
	else
		mysrc="${x}"
	fi
	install ${EXEOPTIONS} "${mysrc}" "${D}${EXEDESTTREE}"
done
