#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [ ${#} -lt 1 ] ; then
	pkgcore_helper_exit "at least one arguement needed"
fi
if [ ! -d "${D}usr/share/info" ] ; then
	install -d "${D}usr/share/info"
	pkgcore_helper_check_exit $? "failed installing base ${D}usr/share/info"
fi

ret=0
for x in "$@" ; do
	if [ -e "${x}" ] ; then
		install -m0644 "${x}" "${D}usr/share/info"
		((ret|=$?))
		gzip -f -9 "${D}usr/share/info/${x##*/}"
		((ret|=$?))
	else
		echo "doinfo: ${x} does not exist" >&2
		((ret|=2))
	fi
done
pkgcore_helper_exit ${ret}
