#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [ $# -lt 1 ] ; then
	pkgcore_helper_exit 1 "at least one arguement needed"
fi

if [ "${1}" == "-r" ] ; then
	DOINSRECUR=y
	shift
else
	DOINSRECUR=n
fi

ret=0
if [ "${INSDESTTREE%${D}*}" == "" ]; then
	pkgcore_helper_exit 2 "do not give \${D} as part of the pathways to doins"
fi

if [ ! -d "${D}${INSDESTTREE}" ]; then
	dodir "${INSDESTTREE}"
	pkgcore_helper_check_exit $? "base dodir of ${INDESTTREE} failed"
fi

ret=0
for x in "$@" ; do
	if [ -L "$x" ] ; then
		cp "$x" "${T}"
		((ret|=$?))
		mysrc="${T}/$(/usr/bin/basename "${x}")"
		((ret|=$?))
	elif [ -d "$x" ] ; then
		if [ "${DOINSRECUR}" == "n" ] ; then
			continue
		fi

		mydir="${INSDESTTREE}/$(basename "${x}")"
		find "${x}" -mindepth 1 -maxdepth 1 -exec \
			env \
				INSDESTTREE="${mydir}" \
				doins -r {} \;
		((ret|=$?))
		continue
	else
		mysrc="${x}"
	fi
	install ${INSOPTIONS} "${mysrc}" "${D}${INSDESTTREE}"
	((ret|=$?))
done

pkgcore_helper_exit ${ret}
