#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [ -z "${PKGCORE_BIN_PATH}" ]; then
	pkgcore_helper_exit -1 "PKGCORE_BIN_PATH is unset, can't load necessary internal libs"
elif [[ $# -lt 1 ]] ; then
	pkgcore_helper_exit 1 "need at least one arguement"
fi
source "${PKGCORE_BIN_PATH}/isolated-functions.lib"
pkgcore_helper_check_exit $? "failed sourcing isolated-functions"


i18n=""

ret=0

for x in "$@" ; do
	if [[ ${x:0:6} == "-i18n=" ]] ; then
		i18n=${x:6}/
		continue
	fi
	if [[ ${x:0:6} == ".keep_" ]] || [[ ${x} == ".keep" ]]; then
		continue
	fi

	suffix=${x##*.}

	# These will be automatically decompressed by ecompressdir.
	if has ${suffix} Z gz bz2 ; then
		realname=${x%.*}
		suffix=${realname##*.}
	fi

	if ! has "${EAPI:-0}" 0 1 && \
		[[ $x =~ (.*)\.([a-z][a-z](_[A-Z][A-Z])?)\.(.*) ]] ; then
		name=${BASH_REMATCH[1]##*/}.${BASH_REMATCH[4]}
		mandir=${BASH_REMATCH[2]}/man${suffix:0:1}
	else
		name=${x##*/}
		mandir=${i18n}man${suffix:0:1}
	fi

	if [[ ${mandir} =~ man[0-9n](f|p|pm)?$ ]] ; then
		if [[ -s ${x} ]] ; then
			if [[ ! -d ${D}/usr/share/man/${mandir} ]] ; then
				install -d "${D}/usr/share/man/${mandir}"
				((ret|=$?))
			fi
			install -m0644 "${x}" "${D}/usr/share/man/${mandir}/${name}"
			((ret|=$?))

		elif [[ ! -e ${x} ]] ; then
			echo "doman: ${x} does not exist" >&2
			((ret|=1))
		fi
	else
		echo "doman: '${x}' is probably not a man page; skipping" >&2
		((ret|=2))
	fi
done

pkgcore_helper_exit ${ret}
