#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

mynum=${#}
if [ ${mynum} -lt 1 ] ; then
	pkgcore_helper_exit 1 "at least one arguement needed"
fi
if [ ! -d "${D}${DESTTREE}/share/locale" ] ; then
	install -d "${D}${DESTTREE}/share/locale/"
	pkgcore_helper_check_exit $? "failed installing base directory ${D}${DESTTREE}/share/locale/"
fi

ret=0

for x in "$@" ; do
	if [ -e "${x}" ] ; then
		mytiny="${x##*/}"
		mydir="${D}${DESTTREE}/share/locale/${mytiny%.*}/LC_MESSAGES"
		if [ ! -d "${mydir}" ] ; then
			install -d "${mydir}"
			((ret|=$?))
		fi
		install -m0644 "${x}" "${mydir}/${MOPREFIX}.mo"
		((ret|=$?))
	else
		echo "${0}: ${x} does not exist" >&2
		((ret|=1))
	fi
done

pkgcore_helper_exit ${ret}
