#!/bin/bash
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if [[ $# -ne 2 ]] ; then
	pkgcore_helper_exit 1 "two arguements needed; got $#"
fi

destdir=${2%/*}
if [[ ! -d ${D}${destdir} ]]; then
	dodir "${destdir}"
	pkgcore_helper_check_exit $? "dodir invocation of ${destdir}"
fi

ln -snf "$1" "${D}$2"
pkgcore_helper_exit $? "symlink creation of $1 -> ${D}${2} failed"
