#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
#
# emake: Supplies some default parameters to GNU make. At the moment the
#        only parameter supplied is -jN, where N is a number of
#        parallel processes that should be ideal for the running host
#        (e.g. on a single-CPU machine, N=2).  The MAKEOPTS variable
#        is set in /etc/make.globals.  We don't source
#        /etc/make.globals here because emake is only called from an
#        ebuild.
[ "${PKGCORE_DEBUG:-0}" != "0" ] && set -x

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

${MAKE:-make} ${MAKEOPTS} ${EXTRA_EMAKE} "$@"
pkgcore_helper_exit $?
