#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

for x in $(find "${D}" -name man -type d -printf '%P\n') ; do
	prepman ${x%/man}
	export prepallman_banner=no
done
