#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if __feature_is_enabled prepstrip || __safe_has nostrip ${RESTRICT}; then
	exit 0
fi

exec prepstrip "${ED}"
