#!/usr/bin/env python

"""Wrapper that adds our custom pylintrc and plugin."""

import sys
import os.path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'lintplugin'))

from pylint import lint

try:
    lint.Run(['--rcfile', os.path.join(
                os.path.dirname(__file__), 'dev-notes', 'pylintrc')] +
             sys.argv[1:])
except KeyboardInterrupt:
    sys.exit(1)

