#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

shopt -s extdebug
source "${PKGCORE_BIN_PATH}/exit-handling.lib" || { echo "failed loading libs"; exit -127; }

if ! ${PKGCORE_PREFIX_SUPPORT=false}; then
	export ED="${D}"
elif [[ "${ED-unset}" == "unset" ]]; then
	echo "The ED variable was missing from the environment, but is required for prefix mode.  Failing".
	exit -1
fi

for x in $(find "${ED}" -name man -type d -printf '%P\n') ; do
	prepman ${x%/man}
	export prepallman_banner=no
done
