#!/usr/bin/env python

"""Commandline wrapper."""

from pkgcore.scripts import filter_env
from pkgcore.util import commandline

if __name__ == '__main__':
    commandline.main(filter_env.argparse_parser)
