name: test

on:
  push:
    branches-ignore: [release-test-*]
  pull_request:
    branches: [master]
  workflow_call:
    inputs:
      release-artifact-id:
        required: false
        type: string
        default: ''
        description: The artifact-id to run the tests against.
      disable-format-check:
        type: string
        default: ''
        description: Disable ruff format check if it is a non empty value

jobs:
  format:
    runs-on: ubuntu-latest
    if: inputs.disable-format-check == ''
    steps:
    - name: Checkout pkgcore
      uses: actions/checkout@v5
    - uses: astral-sh/ruff-action@v3
      with:
        args: "format --check --diff"

  gentoo-regen:
    container:
      image: docker.io/gentoo/stage3:latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pkgcore
      uses: pkgcore/gh-actions/get-source@main
      with:
        artifact-id: ${{ inputs.release-artifact-id }}
        path: pkgcore

    - name: Checkout gentoo
      uses: actions/checkout@v4
      with:
        repository: gentoo/gentoo
        path: gentoo

    - name: Link gentoo repo
      run: ln -s ${PWD}/gentoo /var/db/repos/gentoo

    - name: Install dev-python/pip
      run: getuto && FEATURES="-pid-sandbox -ipc-sandbox -network-sandbox" emerge -j2 -g1 dev-python/pip

    - name: Install pkgcore
      run: pip install --break-system-packages "./pkgcore"

    - name: Run pmaint regen
      working-directory: ./gentoo
      run: pmaint regen --use-local-desc --pkg-desc-index --rsync --force gentoo
